apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybot
  namespace: default
  labels:
    app: mybot
    deployDate: 2019-12-07
    commitHash: 593e9dd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mybot
  template:
    metadata:
      labels:
        app: mybot
        deployDate: 2019-12-07
        commitHash: 593e9dd
    spec:
      restartPolicy: Always
      containers:
        - name: mybot
          image: kanatakita/bot-demo-20191207:593e9dd
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Asia/Tokyo
          envFrom:
          - secretRef:
              name: mybot
