apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mybot
  namespace: default
spec:
  encryptedData:
    SLACK_BOT_APP_ID: AgDAqgxndHv0lm7ubvKLqI/XugWEucf12zG720fMhVwmLkhwwUS7+R/RcXwwZfzpKGV0fDHgbtZRCHsjEI692bd2gevHuj2D+a3MSkfzFKdyUj0LLcDxWoMQe9t3LyhYUdEWUWEC1biGFzNKsnrHDgmCBjLi2HH+/lTUf/ulXHRb9lva1FQZvQxnN9qye3JhiFtuIJdpfHf7RcmyJhOfbXcGESFeqn5fk2uTM9B6LALWF1IZrBkE8dgb3bPuORtkrrMlgf3RLi6pLbc8b7qF3bRapxj/wuG+mbJVF8e2qUsWxS+IcbfuPmr1eBjaBCduM/GSo4XCfmsCt+TZuFZWDdkCY4KLMJSWZPqFThpCqOgF4FVeuJMk9gxmGynXVLUmMjdLlk9Z5FeMvqo+6aWVYQ/RI0VFXmgT73H45hEdwAyvIftV4PTV09xyVq7+U+0s3NI15wEsjXnf+8ZuX1G1FIsW9svQDSA8kHYuqCfWwp+A2fH41EWWxgVJTbamRbOASoNmEuk8n+rHp5Kt7CODZyJfbyTSAW7c1R2UUwELBFykbULe2mlO8h/VQ4/VI9HU6L6nmlAC44f4/5JHwy0JR73U9zwQjDr5TrUjuDTk+57Ib8QgAyiLppNfrirndKRLBOIYjdIQOBEobaV/C+NKg5tQ876Oa6IMPsCipDFPgQJNYlTkOHKOJHHZWECcV2DWjYzWBf+9InRcl/Q=
    SLACK_TOKEN: AgA0I0GvAfq3qk7nofdxVlzWi7e4kLfB8jZV6pPg5yspOK+OmXUJGDLmjfw5p4DRsHJWva8RUHlwXCV6SJqdxGrnlkxouHG+V3ppX/WtnXlgodL9pEVhdaWgm/7uiXlh59uCzzBNJIVFv0NFm5wmwwKcXspeszDAmHqdw6+CZBt9uXdsYqL3/xlUvD0yAalNfv3RNq43sxCVG3aK3zAaqRttb499EAtM3K8v+J7HMoe6taa6D1T2xg9Me4jTIyKYVTl+N7ImUk6RdUnVI66BddIPJRJjl1jRN1i0WHgzH0gIjIctIz4CNJkzO54jqcDXPTynVFuLJJ9RmRqX7hz6e8gi/gYi03aQOaCWKZAMv3zL/EHTqF+6iGmkUDaLdGM1OLbnu15qY+Y2HSouy2cZOcg0M5dIPOg1pMUIbxizTcHgcX3DYkncXuaxNA6UbU1EL9VO0P2gK+xsmQaUyutUU6oRckLSbqgaUY1QmM5OsmDq6bC5PzfzvPEXCF0Q5MW2ZgALl+1UmKDZ4ftzap2lrGKHY5sAX26yci4F17bUYiYb98RPjSr8e5wbi0GWQefiIptCejWYTU9OpHkO5xb9utK9ZCgr1EpmXNFwnDMomFjyovwJnhCTNA6iBPBF/qOEySug+fdNTLbch65JKTOKpTMfV6RBurm4hOocMuQaOYhUX+q4X6myWB1k8ztEEDJGza2cmETyz/HsGt6CB42YBgc3cGS3tJXKso11qOD0CqKCU2rAHwCV4kpw9SI=
  template:
    metadata:
      creationTimestamp: null
      name: mybot
      namespace: default
status: {}

